### ISSUE TITLE
Alignment of existing providers

### ISSUE THREAD

**Issue by TheDuckCow** [CommonMCOBJ/CommonMCOBJ#1]
For record keeping sake, see the following conversations for aligning on the format. We can mark these as done once the scheme is agreed on each front and implemented, might be good to reference also which release in each contains the update when it comes to that point:

- [x] jmc2obj: https://github.com/jmc2obj/j-mc-2-obj/issues/243
- [x] Mineways: https://github.com/erich666/Mineways/issues/125

**Comment by StandingPadAnimations** [comment]
We'll probably create a proper GitHub organization for CommonMCOBJ (just so it's a bit more professional) and have a separate repository that lists OBJ exporters that support the spec.

**Comment by StandingPadAnimations** [comment]
Mineways has now implemented CommonMCOBJ support in the latest beta

**Comment by StandingPadAnimations** [comment]
Closing now that jmc2OBJ supports CommonMCOBJ
