### ISSUE TITLE
Requiring Exporting Proper Block State for All Blocks

### ISSUE THREAD

**Issue by StandingPadAnimations** [CommonMCOBJ/CommonMCOBJ#4]
One area where there seems to be a discrepancy between in-game and exported OBJs is with block states. [Minecraft allows editing blocks state](https://minecraft.wiki/w/Debug_Stick) in-game for creativity purposes. Some examples include:
- Preventing blocks such as walls, fences, and glass panes from being chained
-  Allowing blocks to float that normally wouldn't be allowed (take levers for instance)
- Etc.

Although CommonMCOBJ states as a [non-goal](https://github.com/CommonMCOBJ/CommonMCOBJ#non-goals) 
> - Governing every behavior in Minecraft OBJ exporters; that would be hard to adopt and stifle experimentation,

I think an exception can be made here as it's a vanilla game feature with legitimate use, and expands creative opportunities for artists. Granted, it may cause exports to be slower, but ultimately, exports shouldn't look different from how they look in game.

As such, I propose we add the following section to CommonMCOBJ for V2 of the spec (2026):
> ## Block States
> OBJ exporters following the CommonMCOBJ spec shall export the proper block state for <ins>all blocks</ins>. If an option to only check a pre-determined list of blocks for states exists to speed up exports, it shall <ins>not be enabled by default</ins>.

EDIT 01/04/2024: if wanted, we could change the description of CommonMCOBJ to the following in V2:
> CommonMCOBJ is a spec to allow exported Minecraft OBJs to be closer their in-game counterparts, by creating a common standard for OBJs and creating extra metadata for details that would otherwise be lost.

**Comment by StandingPadAnimations** [comment]
Opening for feedback from OBJ exporter developers

@erich666 @mmdanggg2

**Comment by StandingPadAnimations** [comment]
I will admit this is also a departure from the stated goal of CommnMCOBJ being a standard “to provide extra metadata about the source world and OBJ (that would otherwise be lost) in a standard way.”, and perhaps a pivot to make CommonMCOBJ a more generalized spec is needed, but this would be beneficial for many users

**Comment by Azagwen** [comment]
Passing by to say that doing this would also potentially help future-proof the standard a bit more, if Mojang ever modifies existing blockstates, the additional work to make them work would be reduced (if not null). Because the exporters would read the entire block palette & associated properties fully by default

**Comment by StandingPadAnimations** [comment]
#5 has been created for this proposal
